const movies = {
  // Comedy
  "movie 1": {
    title: "The Hangover",
    year: 2009,
    language: "English",
    director: "Todd Phillips",
    genre: "Comedy",
    rating: 8,
    nationality: "USA",
    mainActor: "Bradley Cooper",
  },
  "movie 2": {
    title: "Superbad",
    year: 2007,
    language: "English",
    director: "Greg Mottola",
    genre: "Comedy",
    rating: 8,
    nationality: "USA",
    mainActor: "Michael Cera",
  },
  "movie 3": {
    title: "عسل أسود",
    year: 2010,
    language: "Arabic",
    director: "Khaled Marei",
    genre: "Comedy",
    rating: 7,
    nationality: "Egypt",
    mainActor: "Ahmed Helmy",
  },
  "movie 4": {
    title: "Al Sayida Al Thaneya",
    year: 2011,
    language: "Arabic",
    director: "Elie Chaccour",
    genre: "Comedy",
    rating: 7,
    nationality: "Lebanese",
    mainActor: "Maguy Abou Ghosn",
  },
  "movie 5": {
    title: "اللمبي 8 جيجا",
    year: 2010,
    language: "Arabic",
    director: "Sherif Arafa",
    genre: "Comedy",
    rating: 7,
    nationality: "Egypt",
    mainActor: "Mohamed Saad",
  },

  // Action
  "movie 6": {
    title: "Mad Max: Fury Road",
    year: 2015,
    language: "English",
    director: "George Miller",
    genre: "Action",
    rating: 8,
    nationality: "Australia",
    mainActor: "Tom Hardy",
  },
  "movie 7": {
    title: "The Dark Knight",
    year: 2008,
    language: "English",
    director: "Christopher Nolan",
    genre: "Action",
    rating: 9,
    nationality: "USA",
    mainActor: "Christian Bale",
  },
  "movie 8": {
    title: "الجزيرة",
    year: 2007,
    language: "Arabic",
    director: "Sherif Arafa",
    genre: "Action",
    rating: 8,
    nationality: "Egypt",
    mainActor: "Ahmed El Sakka",
  },
  "movie 9": {
    title: "مهمة في تبوك",
    year: 2019,
    language: "Arabic",
    director: "Peter Mimi",
    genre: "Action",
    rating: 7,
    nationality: "Egypt",
    mainActor: "Ahmed El Sakka",
  },

  // Drama
  "movie 10": {
    title: "The Insult",
    year: 2017,
    language: "Arabic",
    director: "Ziad Doueiri",
    genre: "Drama",
    rating: 8,
    nationality: "Lebanon",
    mainActor: "Kamel El Basha",
  },
  "movie 11": {
    title: "The Pursuit of Happyness",
    year: 2006,
    language: "English",
    director: "Gabriele Muccino",
    genre: "Drama",
    rating: 9,
    nationality: "USA",
    mainActor: "Will Smith",
  },
  "movie 12": {
    title: "Forrest Gump",
    year: 1994,
    language: "English",
    director: "Robert Zemeckis",
    genre: "Drama",
    rating: 9,
    nationality: "USA",
    mainActor: "Tom Hanks",
  },
  "movie 13": {
    title: "باب الحديد",
    year: 1958,
    language: "Arabic",
    director: "Youssef Chahine",
    genre: "Drama",
    rating: 9,
    nationality: "Egypt",
    mainActor: "Farid Shawki",
  },
  "movie 14": {
    title: "الطريق",
    year: 1956,
    language: "Arabic",
    director: "Hussein Kamal",
    genre: "Drama",
    rating: 8,
    nationality: "Egypt",
    mainActor: "Faten Hamama",
  },

  // Romance
  "movie 15": {
    title: "The Notebook",
    year: 2004,
    language: "English",
    director: "Nick Cassavetes",
    genre: "Romance",
    rating: 8,
    nationality: "USA",
    mainActor: "Ryan Gosling",
  },
  "movie 16": {
    title: "Titanic",
    year: 1997,
    language: "English",
    director: "James Cameron",
    genre: "Romance",
    rating: 9,
    nationality: "USA",
    mainActor: "Leonardo DiCaprio",
  },
  "movie 17": {
    title: "أنت عمري",
    year: 2003,
    language: "Arabic",
    director: "Sherif Arafa",
    genre: "Romance",
    rating: 8,
    nationality: "Egypt",
    mainActor: "Amr Diab",
  },
  "movie 18": {
    title: "الخرساء",
    year: 2007,
    language: "Arabic",
    director: "Samy Kamal",
    genre: "Romance",
    rating: 8,
    nationality: "Egypt",
    mainActor: "Sherine Abdel Wahab",
  },

  // Mix Genres
  "movie 19": {
    title: "The Matrix",
    year: 1999,
    language: "English",
    director: "The Wachowskis",
    genre: "Action-Sci-Fi",
    rating: 9,
    nationality: "USA",
    mainActor: "Keanu Reeves",
  },
  "movie 20": {
    title: "Inception",
    year: 2010,
    language: "English",
    director: "Christopher Nolan",
    genre: "Sci-Fi-Action",
    rating: 9,
    nationality: "USA",
    mainActor: "Leonardo DiCaprio",
  },

  "movie 21": {
    title: "Very Big Shot",
    year: 2015,
    language: "Arabic",
    director: "Mir-Jean Bou Chaaya",
    genre: "Comedy-Action",
    rating: 8,
    nationality: "Lebanon",
    mainActor: "George Khabbaz",
  },
  "movie 22": {
    title: "Bghamdet Ain (بغمضة عين)",
    year: 2019,
    language: "Arabic",
    director: "Ziad Bourji",
    genre: "Comedy-Drama",
    rating: 8,
    nationality: "Lebanon",
    mainActor: "Ziad Bourji",
  },
};
